# Generated by Django 4.2.5 on 2023-09-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicaldayapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='height',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='ridedetails',
            name='height_requirement',
            field=models.JSONField(),
        ),
    ]
