# Generated by Django 4.2.5 on 2023-09-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicaldayapi', '0002_alter_guest_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantdetails',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ridedetails',
            name='description',
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(default='Text', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantdetails',
            name='allergy_friendly',
            field=models.BooleanField(default=2),
            preserve_default=False,
        ),
    ]
